# This workflow will update Python dependencies
# For more information see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

name: Dependency Update

on:
  schedule:
    - cron: "0 4 1 * *"
    # 12am EST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update dependencies
        run: python util/update.py

      - name: Commit new file(s)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: requirements.txt
          commit_message: "[AUTO] dep update #patch"
          commit_user_name: suchak1
          commit_user_email: suchak.krish@gmail.com
          commit_author: Krish Suchak
          push_options: "--force"

      - name: Bump version and push tag
        id: bumpVersion
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: true

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bumpVersion.outputs.new_tag }}