name: Keep Alive

on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine python-dotenv setuptools wheel

      - name: Publish package
        env:
          GITHUB: ${{ secrets.GITHUB }}
          PYPI: ${{ secrets.PYPI }}
        run: |
          python setup.py sdist bdist_wheel
          python util/pypi.py
          python -m twine upload dist/*
