# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Model Pipeline

on:
  push:
    branches:
      - feature/strategy-builder
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - window: 7
          - window: 7
            extra: true
          - window: 14
          - window: 14
            extra: true
          - window: 30
          - window: 30
            extra: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install crypto-js
        run: |
          npm i crypto-js@4.1.1

      - name: Decrypt script
        env:
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
        run: |
          node util/decrypt

      - name: Create model
        env:
          WINDOW: ${{ matrix.window }}
          EXTRA: ${{ matrix.extra }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          python encrypted/create_model.py
