# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily Update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Decrypt token
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          scripts/decrypt.sh
      - name: Login to Robinhood
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python scripts/login.py
      - name: Encrypt token
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          scripts/encrypt.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Krish Suchak
          author_email: suchak.krish@gmail.com
          message: "[AUTO] OAuth token refresh"
          add: "robinhood.pickle.gpg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
